apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
spec:
  project: default
  source:
    chart: cilium
    repoURL: https://helm.cilium.io/
    targetRevision: 1.15.4
    helm:
      releaseName: cilium
      values: |
        kubeProxyReplacement: true
        ipv4:
          enabled: true
        ipam:
          mode:
            kubernetes
        hubble:
          enabled: true
          metrics:
            enabled:
              - dns:query;ignoreAAAA
              - drop:sourceContext=identity;destinationContext=identity
              - tcp
              - flow
              - icmp
              - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction
              - policy:sourceContext=app|workload-name|pod|reserved-identity;destinationContext=app|workload-name|pod|dns|reserved-identity;labelsContext=source_namespace,destination_namespace
            enableOpenMetrics: true
            serviceMonitor:
              enabled: true
              labels:
                release: prometheus
        operator:
          prometheus:
            enabled: true
            serviceMonitor:
              enabled: true
              labels:
                release: prometheus
          pprof:
            enabled: true
        prometheus:
          enabled: true
          trustCRDsExist: true
          serviceMonitor:
            enabled: true
            labels:
              release: prometheus
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true