# https://blog.pinfort.me/posts/myhome-elastic-cloud-on-kubernetes/

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-operator-crds
spec:
  project: default
  source:
    chart: eck-operator-crds
    repoURL: https://helm.elastic.co/
    targetRevision: 2.12.1
    helm:
      releaseName: eck-operator-crds
  destination:
    server: https://kubernetes.default.svc
    namespace: elasticsearch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-operator
spec:
  project: default
  source:
    chart: eck-operator
    repoURL: https://helm.elastic.co/
    targetRevision: 2.12.1
    helm:
      releaseName: eck-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: elasticsearch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true