# https://blog.pinfort.me/posts/myhome-elastic-cloud-on-kubernetes/

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-operator-crds
spec:
  project: default
  source:
    chart: eck-operator-crds
    repoURL: https://helm.elastic.co/
    targetRevision: 2.12.1
    helm:
      releaseName: eck-operator-crds
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-operator
spec:
  project: default
  source:
    chart: eck-operator
    repoURL: https://helm.elastic.co/
    targetRevision: 2.12.1
    helm:
      releaseName: eck-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-stack
spec:
  project: default
  source:
    chart: eck-stack
    repoURL: https://helm.elastic.co/
    targetRevision: 0.10.0
    helm:
      releaseName: eck-stack
      valueFiles:
      - https://raw.githubusercontent.com/elastic/cloud-on-k8s/2.12/deploy/eck-stack/examples/agent/fleet-agents.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-server-ingress
  namespace: elastic-stack
spec:
  ingressClassName: nginx
  rules:
  - host: kibana.bira.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kibana-kb-http
            port:
              number: 5601