apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-crd
  namespace: asdff
spec:
  project: default
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    path: charts/kube-prometheus-stack/crds/
    targetRevision: kube-prometheus-stack-58.4.0
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: asdff
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
spec:
  destination:
    name: ''
    namespace: asdff
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 58.4.0
    chart: kube-prometheus-stack
    helm:
      releaseName: kube-prometheus-stack
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
