apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-crd
spec:
  project: default
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    path: charts/kube-prometheus-stack/charts/crds/
    targetRevision: kube-prometheus-stack-58.2.2
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
spec:
  destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 58.2.2
    chart: kube-prometheus-stack
    helm:
      skipCrds: true
      releaseName: kube-prometheus-stack
      values: |
        grafana:
          sidecar:
            datasources:
              enabled: false
              defaultDatasourceEnabled: false
              isDefaultDatasource: false
          defaultDashboardsTimezone: Asia/Tokyo
          plugins:
            - grafana-piechart-panel
            - isovalent-hubble-datasource
            - grafana-sentry-datasource
          grafana.ini:
            date_formats:
              default_timezone: Asia/Tokyo
          persistence:
            enabled: true
            size: 10Gi
          datasources:
            datasources.yaml:
              apiVersion: 1
              datasources:
                - name: Prometheus
                  type: prometheus
                  url: http://kube-prometheus-stack-prometheus.monitoring:9090
                  isDefault: true
                - name: Loki
                  type: loki
                  url: http://loki:3100
                  isDefault: false
                - name: Alertmanager
                  type: alertmanager
                  url: http://kube-prometheus-stack-alertmanager.monitoring:9093
                  jsonData:
                    implementation: prometheus
                    handleGrafanaManagedAlerts: false
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-server-ingress
  namespace: monitoring
spec:
  ingressClassName: nginx
  rules:
  - host: grafana.bira.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kube-prometheus-stack-grafana
            port:
              number: 80
